let sermons = [
  {
    bibleText: '',
    broadcaster: {
      aboutUs:
        'It’s hard to find an entertaining experience the whole family can enjoy that is both captivating and character building. We know how you feel. You deserve an experience you can trust—an experience that makes a difference, now and for eternity.\n\nFor more than 10 years we’ve produced life-transforming audio dramas adapted from rare literary treasures that are founded on biblical truth. Each story is brought to life by the talent of world-class actors from productions such as Lord of the Rings, Downton Abbey, Star Wars, Pirates of the Caribbean, Adventures in Odyssey, and many more. Lamplighter Theatre is just what you’ve been looking for!',
      address: 'Lamplighter Ministries\n23 State St.\nMount Morris NY 14510',
      albumArtURL:
        'https://vps.sermonaudio.com/resize_image/sources/podcast/{size}/{size}/lamplighter-01.jpg',
      bibleVersion: null,
      broadcasterID: 'lamplighter',
      canWebcast: false,
      country: 'USA',
      denomination: null,
      displayName: 'Lamplighter Theatre Audio Drama',
      facebookUsername: 'lamplighterministries',
      homePageURL: 'http://lamplighter.net',
      idCode: '63267',
      imageURL:
        'https://media.sermonaudio.com/gallery/photos/sources/lamplighter-01.jpg',
      latitude: 42.7248191,
      listenLineNumber: null,
      location: 'Mount Morris, New York',
      longitude: -77.8764317,
      minister: 'Mark Hamby',
      phone: '888-246-7735',
      serviceTimes: null,
      serviceTimesArePreformatted: false,
      shortName: 'Lamplighter Theatre',
      twitterUsername: 'lamplighterbook',
      type: 'broadcaster',
      vacantPulpit: false,
      webcastInProgress: false,
    },
    displayEventType: 'Audio Book',
    displayTitle: "Teddy's Button - The Gospel",
    documentDownloadCount: 0,
    downloadCount: 1170,
    eventType: 'Audio Book',
    externalLink: null,
    fullTitle: "Lamplighter Theatre Moments - Teddy's Button - The Gospel",
    keywords: 'Lamplighter LamplighterTheatre MarkHamby',
    languageCode: 'en',
    media: {
      audio: [
        {
          adaptiveBitrate: false,
          audioCodec: 'mp3',
          bitrate: 73,
          downloadURL:
            'https://mp3.sermonaudio.com/filearea/9131918851854/9131918851854.mp3',
          duration: 121,
          live: false,
          mediaType: 'mp3',
          streamURL:
            'https://mp3.sermonaudio.com/filearea/9131918851854/9131918851854.mp3',
          thumbnailImageURL: null,
          type: 'media',
          videoCodec: null,
        },
        {
          adaptiveBitrate: false,
          audioCodec: 'mp3',
          bitrate: 16,
          downloadURL:
            'https://mp3.sermonaudio.com/16kbps/9131918851854/9131918851854.mp3',
          duration: 121,
          live: false,
          mediaType: 'mp3',
          streamURL:
            'https://mp3.sermonaudio.com/16kbps/9131918851854/9131918851854.mp3',
          thumbnailImageURL: null,
          type: 'media',
          videoCodec: null,
        },
      ],
      text: [],
      type: 'media_set',
      video: [],
    },
    moreInfoText: 'Purchase the full audio drama at www.lamplighter.net.',
    pickDate: '2019-09-17',
    preachDate: '2019-09-13',
    publishDate: '2019-09-13',
    publishTimestamp: 1568398132,
    series: {
      broadcasterID: 'lamplighter',
      count: 42,
      earliest: '2019-09-13',
      latest: '2019-09-13',
      seriesID: 99672,
      title: 'Lamplighter Theatre Moments',
      type: 'series',
      updated: 1568398594,
    },
    sermonID: '9131918851854',
    speaker: {
      albumArtURL:
        'https://vps.sermonaudio.com/resize_image/speakers/podcast/{size}/{size}/HambyMark.jpg',
      bio: null,
      displayName: 'Mark Hamby',
      mostRecentPreachDate: null,
      portraitURL: 'https://media.sermonaudio.com/gallery/photos/HambyMark.jpg',
      roundedThumbnailImageURL:
        'https://media.sermonaudio.com/gallery/photos/thumbnails/HambyMark.PNG',
      sortName: 'Hamby, Mark',
      type: 'speaker',
    },
    subtitle: 'Lamplighter Theatre Moments',
    type: 'sermon',
    updateDate: 1568754543,
    videoDownloadCount: 0,
  },
  {
    bibleText: 'Luke 11:5-13',
    broadcaster: {
      aboutUs:
        '"Kindred Community Church Exists to Glorify God by Making and Maturing Disciples of Jesus Christ Throughout the World."',
      address:
        'Kindred Community Church\n8712 East Santa Ana Canyon Road\nAnaheim Hills, CA 92808',
      albumArtURL:
        'https://vps.sermonaudio.com/resize_image/sources/podcast/{size}/{size}/philipdecourcy.jpg',
      bibleVersion: null,
      broadcasterID: 'philipdecourcy',
      canWebcast: false,
      country: 'USA',
      denomination: null,
      displayName: 'Kindred Community Church',
      facebookUsername: null,
      homePageURL: 'http://www.kindredchurch.org',
      idCode: '10653',
      imageURL:
        'https://media.sermonaudio.com/gallery/photos/sources/philipdecourcy.jpg',
      latitude: 33.864313,
      listenLineNumber: null,
      location: 'Anaheim Hills, California',
      longitude: -117.722593,
      minister: 'Philip De Courcy',
      phone: '714-282-9941',
      serviceTimes: 'Sunday Services ... 8:45 a.m. & 10:30 a.m.',
      serviceTimesArePreformatted: true,
      shortName: 'Kindred Community Church',
      twitterUsername: null,
      type: 'broadcaster',
      vacantPulpit: false,
      webcastInProgress: false,
    },
    displayEventType: 'Sunday Service',
    displayTitle: 'Pray Until Something Happens',
    documentDownloadCount: 0,
    downloadCount: 2360,
    eventType: 'Sunday Service',
    externalLink: null,
    fullTitle: 'Pray Until Something Happens',
    keywords: 'prayer',
    languageCode: 'en',
    media: {
      audio: [
        {
          adaptiveBitrate: false,
          audioCodec: 'mp3',
          bitrate: 64,
          downloadURL:
            'https://mp3.sermonaudio.com/filearea/111161137330/111161137330.mp3',
          duration: 1874,
          live: false,
          mediaType: 'mp3',
          streamURL:
            'https://mp3.sermonaudio.com/filearea/111161137330/111161137330.mp3',
          thumbnailImageURL: null,
          type: 'media',
          videoCodec: null,
        },
        {
          adaptiveBitrate: false,
          audioCodec: 'mp3',
          bitrate: 16,
          downloadURL:
            'https://mp3.sermonaudio.com/16kbps/111161137330/111161137330.mp3',
          duration: 1874,
          live: false,
          mediaType: 'mp3',
          streamURL:
            'https://mp3.sermonaudio.com/16kbps/111161137330/111161137330.mp3',
          thumbnailImageURL: null,
          type: 'media',
          videoCodec: null,
        },
      ],
      text: [],
      type: 'media_set',
      video: [],
    },
    moreInfoText: null,
    pickDate: '2019-09-30',
    preachDate: '2016-10-30',
    publishDate: '2016-11-01',
    publishTimestamp: 1478014653,
    series: null,
    sermonID: '111161137330',
    speaker: {
      albumArtURL:
        'https://vps.sermonaudio.com/resize_image/speakers/podcast/{size}/{size}/DeCourcyPhilip-01.jpg',
      bio:
        'Philip De Courcy is the senior pastor of Kindred Community Church in Anaheim Hills, California, and speaker on the daily radio program, Know The Truth.',
      displayName: 'Philip De Courcy',
      mostRecentPreachDate: null,
      portraitURL:
        'https://media.sermonaudio.com/gallery/photos/DeCourcyPhilip-01.jpg',
      roundedThumbnailImageURL:
        'https://media.sermonaudio.com/gallery/photos/thumbnails/DeCourcyPhilip-01.PNG',
      sortName: 'De Courcy, Philip',
      type: 'speaker',
    },
    subtitle: null,
    type: 'sermon',
    updateDate: 1551815166,
    videoDownloadCount: 0,
  },
  {
    bibleText: 'Philippians 4:6-6',
    broadcaster: {
      aboutUs:
        'The largest and most trusted library of audio sermons from conservative churches and ministries worldwide with over one million sermons. The mission and purpose of SermonAudio is the preservation and propagation of Bible preaching to this generation and the next.',
      address: 'SERMONAUDIO\nOffice HQ, Greenville\nSouth Carolina, USA',
      albumArtURL:
        'https://vps.sermonaudio.com/resize_image/sources/podcast/{size}/{size}/misc3-07.jpg',
      bibleVersion: 'KJV',
      broadcasterID: 'misc',
      canWebcast: true,
      country: 'USA',
      denomination: null,
      displayName: 'SermonAudio Classics',
      facebookUsername: 'sermonaudio',
      homePageURL: 'http://www.sermonaudio.com',
      idCode: '00000',
      imageURL:
        'https://media.sermonaudio.com/gallery/photos/sources/misc3-07.jpg',
      latitude: 34.846897,
      listenLineNumber: null,
      location: 'Office HQ, Greenville SC',
      longitude: -82.402767,
      minister: 'Multiple Speakers',
      phone: '864-214-5111',
      serviceTimes: null,
      serviceTimesArePreformatted: false,
      shortName: 'SermonAudio Classics',
      twitterUsername: 'SermonAudio',
      type: 'broadcaster',
      vacantPulpit: false,
      webcastInProgress: false,
    },
    displayEventType: 'Classic Audio',
    displayTitle: 'In Everything By Prayer',
    documentDownloadCount: 0,
    downloadCount: 12220,
    eventType: 'Classic Audio',
    externalLink: null,
    fullTitle: 'In Everything By Prayer',
    keywords: null,
    languageCode: 'en',
    media: {
      audio: [
        {
          adaptiveBitrate: false,
          audioCodec: 'mp3',
          bitrate: 16,
          downloadURL:
            'https://mp3.sermonaudio.com/filearea/11240215752/11240215752.mp3',
          duration: 2154,
          live: false,
          mediaType: 'mp3',
          streamURL:
            'https://mp3.sermonaudio.com/filearea/11240215752/11240215752.mp3',
          thumbnailImageURL: null,
          type: 'media',
          videoCodec: null,
        },
      ],
      text: [],
      type: 'media_set',
      video: [],
    },
    moreInfoText: null,
    pickDate: '2019-10-07',
    preachDate: '1960-01-01',
    publishDate: '2002-11-24',
    publishTimestamp: 1038121073,
    series: null,
    sermonID: '11240215752',
    speaker: {
      albumArtURL:
        'https://vps.sermonaudio.com/resize_image/speakers/podcast/{size}/{size}/tozer.jpg',
      bio:
        "A 20th-century prophet\" they called him even in his lifetime. For 31 years he was pastor of Southside Alliance Church in Chicago, where his reputation as a man of God was citywide. Concurrently he became editor of Alliance Life, a responsibility he fulfilled until his death in 1963. His greatest legacy to the Christian world has been his 30 books. Because A.W. Tozer lived in the presence of God he saw clearly and he spoke as a prophet to the church. He sought for God's honor with the zeal of Elijah and mourned with Jeremiah at the apostasy of God's people. But he was not a prophet of despair. His writings are messages of concern. They expose the weaknesses of the church and denounce compromise. They warn and exhort. But they are messages of hope as well, for God is always there, ever faithful to restore and to fulfill His Word to those who hear and obey.",
      displayName: 'A. W. Tozer',
      mostRecentPreachDate: null,
      portraitURL: 'https://media.sermonaudio.com/gallery/photos/tozer.jpg',
      roundedThumbnailImageURL:
        'https://media.sermonaudio.com/gallery/photos/thumbnails/tozer.PNG',
      sortName: 'Tozer, A. W.',
      type: 'speaker',
    },
    subtitle: null,
    type: 'sermon',
    updateDate: 1551815166,
    videoDownloadCount: 0,
  },
];

let versesOfTheDay = [
  {
    verse : "John 3:16",
    verseText: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth on him should not perish, but have eternal life. ... For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
    date:"27 Oct"
  },
  {
    verse : "Psalm 5:3",
    verseText: "In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly.",
    date:"26 Oct"
  },
  {
    verse : "Romans 8:18",
    verseText: " I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.",
    date:"25 Oct"
  },
]

export { sermons,versesOfTheDay };
